language: objective-c
osx_image: xcode61

branches:
  only:
  - master
notifications:
  email: false

before_install:
  - gem install cocoapods
  - gem install xcpretty

before_script: pod install

script: bash ./.travis_test.sh
